import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Prividers";
import dynamic from "next/dynamic";
import LeftBar from "@/components/LeftBar";
const NavBar = dynamic(() => import("@/components/NavBar"), {
  ssr: false,
  loading: () => <div className=""></div>,
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Launchifi Tool",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <NavBar className="z-30" />
          <LeftBar />
          <div className="flex">
            <div className="flex justify-center items-center w-full pt-28">
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
