import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import dynamic from "next/dynamic";
import LeftBar from "@/components/LeftBar";
import Footer from "@/components/Footer";
const NavBar = dynamic(() => import("@/components/NavBar"), { ssr: false,});

const BackImage = dynamic(()=> import("@/components/BackImage"),{ ssr: false})

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Launchifi Tool",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <NavBar className="z-30" />
          {/* <LeftBar /> */}
          <BackImage />
          <div className="flex w-full overflow-hidden min-h-[calc(100vh-50px)]">
            <div className="flex justify-center w-full pt-28">
              {children}
            </div>
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
